# Generated by Django 3.2.7 on 2021-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculties',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
